@startwbs

<style>
wbsDiagram {
  node {
    BackgroundColor white
    LineColor black
    FontColor black
  }

  arrow {
    LineColor black
  }

  :depth(0) {
    arrow {
      LineColor white
    }
  }

  .hidden {
    BackgroundColor white
    LineColor white
    FontColor white
  }
}
</style>

legend bottom right
  //X// = 1..N (factory index)

  == acop (accessControlOperations) ==
  CREATE = 1
  RETRIEVE = 2
  UPDATE = 4
  DELETE = 8
  NOTIFY = 16
  DISCOVERY = 32

  3 = CREATE + RETRIEVE
  15 = CREATE + RETRIEVE + UPDATE + DELETE

  == enc.net (notificationEventType) ==
  3 = Create of Direct Child Resource
endlegend

* Root <<hidden>>

** <CSEBase> IN-CSE
*** <remoteCSE> MN-CSE-//X//

*** <ACP> acp-fl-control\n[IN-AE: 15, MN-AE-//X//: 3]
*** <ACP> acp-global-model\n[IN-AE: 15, MN-AE-//X//: 2]
*** <ACP> acp-local-update-mn//X//\n[IN-AE: 3, MN-AE-//X//: 1]

*** <AE> IN-AE (Aggregator)
**** <CNT> cnt-fl-control\n[acpi: acp-fl-control]
***** <SUB> sub-fl-control-mn//X//\n[nu: MN-AE-//X//, net: 3]

**** <CNT> cnt-global-model\n[acpi: acp-global-model]

**** <CNT> cnt-local-updates
***** <CNT> cnt-mn//X//\n[acpi: acp-local-update-mn//X//]
****** <SUB> sub-in-dropbox-mn//X//\n[nu: IN-AE, net: 3]


** <CSEBase> MN-CSE-//X//
*** <remoteCSE> IN-CSE

*** <ACP> acp-sensor-data-//X//\n[ADN-AE-//X//: 15, MN-AE-//X//: 3]
*** <ACP> acp-local-model-//X//\n[MN-AE-//X//: 15]

*** <AE> ADN-AE-//X// (Sensor Producer)
**** <CNT> cnt-sensor-data\n[acpi: acp-sensor-data-//X//]
***** <CIN> sensor-data metadata
***** <SUB> sub-sensor-data-//X//\n[nu: MN-AE-//X//, net: 3]

*** <AE> MN-AE-//X// (Factory Gateway / Trainer)
**** <CNT> cnt-local-model\n[acpi: acp-local-model-//X//]

@endwbs